### ISSUE TITLE
During executing

### ISSUE THREAD

**Issue by karthika-devi** [Harsh24893/EmotionRecognition#1]
word2vec = vocab_to_word2vec("GoogleNews-vectors-negative300.bin", vocabulary)
What does the GoogleNews-vectors-negative300.bin file means and where i get this and what is the process of prepare file in Baseline directiry

**Comment by naikzinal** [comment]
It is a model which is train by google for word vector . you can download from this link https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit

**Comment by naikzinal** [comment]
During the run python train_cnn.py i found the following error plese any body can help me..Thank you

zinal@zinal-Vostro-1540:~/Downloads/EmotionRecognition-master$ python train_cnn.py
/home/zinal/.local/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "train_cnn.py", line 172, in <module>
    train_cnn()
  File "train_cnn.py", line 20, in train_cnn
    x_raw, y_raw, df, labels, embedding_mat = data_helper.load_data_and_labels(train_file)
  File "/home/zinal/Downloads/EmotionRecognition-master/data_helper.py", line 31, in load_data_and_labels
    df = pd.read_csv('iseardataset.csv')
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 529, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 295, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 612, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 747, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1119, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 353, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3246)
  File "pandas/parser.pyx", line 591, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6111)
IOError: File iseardataset.csv does not exist

**Comment by naikzinal** [comment]
dear @Harsh24893  with the help of python train_cnn.py  i complete my training phase. but now how i can test the model. or which are the steps for testing.
please help me thank you.

**Comment by muskybl** [comment]
How can i use trained model and predict it based on new test ? Thank you
